### ISSUE TITLE
请问能否添加一个自动卖掉打怪掉落的装备的功能？

### ISSUE THREAD

**Issue by ghost** [Couy69/vue-idle-game#15]
每次挂机，都会因为背包塞满了没用的装备而停止。我希望能有一个自动把掉落的装备卖掉的功能。当然卖掉的装备等级可以由玩家设置，比如我只想留着史诗级的装备，低于这个等级的装备都自动卖掉，最后因为背包里塞满了史诗级的装备而停止打怪

**Comment by cratexnet** [comment]
+1，只留红的橙的就好了，话说除了武器我还没发现衣服和首饰有红装？
