### ISSUE TITLE
装备独特武器的时候商店里的普通武器也会显示成红框

### ISSUE THREAD

**Issue by placy3** [Couy69/vue-idle-game#17]
![image](https://user-images.githubusercontent.com/25332960/98509620-7bab5280-229c-11eb-80d8-c305a1e131b4.png)
小bug

**Comment by placy3** [comment]
有时候重新进入商店会变回白色
似乎跟鼠标碰到的上一个装备颜色有关

**Comment by Couy69** [comment]
感谢，之后会修复
