### ISSUE TITLE
感谢作者提供这么好玩的游戏

### ISSUE THREAD

**Issue by fuhouyin** [Couy69/vue-idle-game#28]
之前一直有想做类似的游戏 但又不知道如何入手，看到这个确实给了我很大很大的启发，感谢作者

存档是base64加密两遍对吗，我试着改了下数据，导入也是完全没有问题的
![image](https://user-images.githubusercontent.com/25275051/187699550-401aff9d-ecd2-41e6-9bad-6f4b8f7fc8cd.png)

**Comment by MrJxySteven** [comment]
麻烦 教教我可以吗？

**Comment by MrJxySteven** [comment]
方便 加我 QQ ？

**Comment by fuhouyin** [comment]
> 麻烦 教教我可以吗？

这是我fork的项目 并不是我写的，请教还是去找原作者吧，修改也很简单，这游戏存储的数据是base64加密后的json数据，网上找base64解密工具即可，然后修改对应属性值，再将修改的值加密回去，然后导入游戏即可，这本身没有什么难的，不过用这种方式做游戏存档我真的是眼前一亮
