### ISSUE TITLE
第一次得到装备时鼠标悬停不显示和现有装备对比

### ISSUE THREAD

**Issue by stcheng** [Couy69/vue-idle-game#8]
<img width="1043" alt="bug" src="https://user-images.githubusercontent.com/2702699/98020888-72ac1400-1db8-11eb-92f5-f49ef32bedc9.png">
如图，当第一次获得装备时鼠标悬停并没有与目前装备的能力值比较。当第一次装备以后此bug消失。

**Comment by Couy69** [comment]
已修复
